version: '3.7'
services:
  server-dev:
    networks:
      - recipe-app-network
    image: doughtnerd/template-server:dev
    container_name: 'recipes_server'
    build:
      context: ./recipe-server
      target: dev
    command: "./bin/wait-for-it.sh mysql:3306 --timeout=60 -- npm run start:dev"
    ports:
      - 3005:3005
      - 9229:9229
    environment:
        - PORT=3005
    volumes: 
      - ./recipe-server:/usr/src/app
      - /usr/src/app/node_modules

  mysql: 
    networks:
      - recipe-app-network
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "recipe-app-db"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_PORT: 3306

networks: 
  recipe-app-network: